import { cookies } from "next/headers";
import { notFound, redirect } from "next/navigation";
import { auth } from "@/auth";
import { GrowthShell } from "@/components/growth/growth-shell";
import { getExperienceModeCookieName, resolveExperienceMode } from "@/lib/experience-mode";
import { normalizeLanguage, getLanguageLocale } from "@/lib/i18n";
import { customerSegments, getCustomerSegmentLabel } from "@/lib/customers/segments";
import { isOfferCurrentlyValid } from "@/lib/offers/eligibility";
import { canAccessBusiness, canManageBusiness } from "@/lib/permissions";
import prisma from "@/lib/prisma";
import { createOfferAction, toggleOfferStatusAction, updateOfferAction } from "./actions";

type Props = { params: Promise<{ slug: string }>; searchParams: Promise<{ success?: string; error?: string }> };
function date(value: Date | null, language: "AR" | "EN") { return value ? new Intl.DateTimeFormat(getLanguageLocale(language), { dateStyle: "medium", timeZone: "Africa/Cairo" }).format(value) : language === "AR" ? "مفتوح" : "Open-ended"; }
function eligibility(value: string, segment: string | null, language: "AR" | "EN") { if (value === "VIP") return language === "AR" ? "عملاء VIP" : "VIP customers"; if (value === "SEGMENT") return language === "AR" ? `شريحة: ${segment}` : `Segment: ${segment}`; return language === "AR" ? "كل العملاء النشطين" : "All active customers"; }

export default async function OffersPage({ params, searchParams }: Props) {
  const session = await auth(); if (!session?.user) redirect("/login"); const { slug } = await params; const query = await searchParams;
  const [user, business] = await Promise.all([prisma.user.findUnique({ where: { id: session.user.id }, select: { language: true, role: true, experienceAccess: true } }), prisma.business.findUnique({ where: { slug }, select: { id: true, slug: true, name: true, offers: { orderBy: [{ isActive: "desc" }, { updatedAt: "desc" }] } } })]);
  if (!business) notFound(); if (!canAccessBusiness(session.user, business.id)) redirect("/dashboard"); const manage = canManageBusiness(session.user, business.id);
  const language = normalizeLanguage(user?.language); const mode = resolveExperienceMode((await cookies()).get(getExperienceModeCookieName(session.user.id))?.value, user?.role ?? session.user.role, user?.experienceAccess); const simple = mode === "SIMPLE"; const now = new Date();
  return <GrowthShell slug={business.slug} businessName={business.name} area="offers" language={language} experienceMode={mode} title={language === "AR" ? "العروض" : "Offers"} description={language === "AR" ? "العروض حوافز للعرض فقط؛ لا تغيّر الأرصدة أو قواعد الولاء." : "Offers are display-only incentives; they do not change balances or loyalty rules."}>
    {query.success ? <p role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-900">{language === "AR" ? "تم حفظ العرض." : "Offer saved."}</p> : null}{query.error ? <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-900">{language === "AR" ? "تعذر حفظ العرض. راجع الجمهور والتواريخ." : "We could not save the offer. Review audience and dates."}</p> : null}
    <section className={`grid gap-6 ${manage && !simple ? "lg:grid-cols-[minmax(0,1fr)_22rem]" : ""}`}><div className="order-2 space-y-4 lg:order-1"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label={language === "AR" ? "نشطة الآن" : "Active now"} value={business.offers.filter((offer) => isOfferCurrentlyValid(offer, now)).length} /><Metric label={language === "AR" ? "قادمة" : "Upcoming"} value={business.offers.filter((offer) => offer.isActive && offer.validFrom && offer.validFrom > now).length} /><Metric label={language === "AR" ? "منتهية" : "Expired"} value={business.offers.filter((offer) => offer.validUntil && offer.validUntil < now).length} /><Metric label={language === "AR" ? "غير نشطة" : "Inactive"} value={business.offers.filter((offer) => !offer.isActive).length} /></div>
      {business.offers.length === 0 ? <Empty language={language} /> : business.offers.map((offer) => { const current = isOfferCurrentlyValid(offer, now); const state = !offer.isActive ? (language === "AR" ? "غير نشط" : "Inactive") : offer.validFrom && offer.validFrom > now ? (language === "AR" ? "قادم" : "Upcoming") : offer.validUntil && offer.validUntil < now ? (language === "AR" ? "منتهٍ" : "Expired") : (language === "AR" ? "نشط" : "Active"); return <article key={offer.id} className="rounded-lg border border-border bg-surface p-5"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div><div className="flex flex-wrap gap-2"><h2 className="font-semibold text-slate-950">{offer.name}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${current ? "bg-emerald-100 text-emerald-900" : "bg-slate-100 text-slate-700"}`}>{state}</span></div><p className="mt-1 text-sm text-slate-600">{eligibility(offer.eligibility, offer.segment, language)}</p><p className="mt-1 text-sm text-slate-500">{date(offer.validFrom, language)} — {date(offer.validUntil, language)}</p>{offer.description ? <p className="mt-3 text-sm text-slate-700">{offer.description}</p> : null}</div>{manage ? <form action={toggleOfferStatusAction.bind(null, business.slug, offer.id, !offer.isActive)}><button type="submit" className="min-h-11 rounded-md border border-border px-4 text-sm font-semibold text-primary">{offer.isActive ? (language === "AR" ? "إيقاف" : "Deactivate") : (language === "AR" ? "تفعيل" : "Activate")}</button></form> : <span className="text-sm font-semibold text-slate-500">{language === "AR" ? "عرض فقط" : "View only"}</span>}</div>{manage && !simple ? <details className="mt-4 rounded-md bg-surface-subtle p-4"><summary className="cursor-pointer font-semibold text-primary">{language === "AR" ? "تعديل ومعاينة" : "Edit and preview"}</summary><p className="mt-3 text-sm text-slate-600">{current ? (language === "AR" ? "سيظهر العرض فقط للعملاء المؤهلين." : "The offer is visible only to eligible customers.") : (language === "AR" ? "العرض غير ظاهر للعملاء حاليًا." : "This offer is not currently visible to customers.")}</p><OfferForm action={updateOfferAction.bind(null, business.slug, offer.id)} language={language} offer={offer} /></details> : null}</article>; })}</div>
      {manage && !simple ? <aside className="order-1 h-fit rounded-lg border border-border bg-surface p-5 lg:order-2"><h2 className="font-semibold text-slate-950">{language === "AR" ? "إضافة عرض" : "Add offer"}</h2><OfferForm action={createOfferAction.bind(null, business.slug)} language={language} /></aside> : null}</section>
  </GrowthShell>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-lg border border-border bg-surface p-3"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-xl font-semibold text-slate-950">{value}</p></div>; }
function Empty({ language }: { language: "AR" | "EN" }) { return <section className="rounded-lg border border-dashed border-border bg-surface-subtle p-6 text-center"><h2 className="font-semibold text-slate-950">{language === "AR" ? "لا توجد عروض بعد" : "No offers yet"}</h2><p className="mt-2 text-sm text-slate-600">{language === "AR" ? "أضف عرضًا عند الحاجة، من دون أي تأثير مالي." : "Add an offer when needed, without any financial effect."}</p></section>; }
function OfferForm({ action, language, offer }: { action: (data: FormData) => void; language: "AR" | "EN"; offer?: { name: string; description: string | null; validFrom: Date | null; validUntil: Date | null; eligibility: string; segment: string | null } }) { const label = (ar: string, en: string) => language === "AR" ? ar : en; return <form action={action} className="mt-4 grid gap-3"><label className="text-sm font-semibold text-slate-700">{label("الاسم", "Name")}<input name="name" required minLength={2} maxLength={100} defaultValue={offer?.name} className="mt-1 min-h-11 w-full rounded-md border border-border bg-surface px-3" /></label><label className="text-sm font-semibold text-slate-700">{label("الوصف", "Description")}<textarea name="description" rows={3} maxLength={500} defaultValue={offer?.description ?? ""} className="mt-1 w-full rounded-md border border-border bg-surface p-3" /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">{label("يبدأ", "Starts")}<input name="validFrom" type="date" defaultValue={offer?.validFrom?.toISOString().slice(0, 10)} className="mt-1 min-h-11 w-full rounded-md border border-border bg-surface px-3" /></label><label className="text-sm font-semibold text-slate-700">{label("ينتهي", "Ends")}<input name="validUntil" type="date" defaultValue={offer?.validUntil?.toISOString().slice(0, 10)} className="mt-1 min-h-11 w-full rounded-md border border-border bg-surface px-3" /></label></div><label className="text-sm font-semibold text-slate-700">{label("الأهلية", "Eligibility")}<select name="eligibility" defaultValue={offer?.eligibility ?? "ALL"} className="mt-1 min-h-11 w-full rounded-md border border-border bg-surface px-3"><option value="ALL">{label("كل العملاء النشطين", "All active customers")}</option><option value="VIP">VIP</option><option value="SEGMENT">{label("شريحة", "Segment")}</option></select></label><label className="text-sm font-semibold text-slate-700">{label("الشريحة (عند الاختيار)", "Segment (when selected)")}<select name="segment" defaultValue={offer?.segment ?? ""} className="mt-1 min-h-11 w-full rounded-md border border-border bg-surface px-3"><option value="">—</option>{customerSegments.map((segment) => <option key={segment} value={segment}>{getCustomerSegmentLabel(segment, language)}</option>)}</select></label><button type="submit" className="min-h-11 rounded-md bg-primary px-4 font-semibold text-white">{label(offer ? "حفظ التعديلات" : "إضافة عرض", offer ? "Save changes" : "Add offer")}</button></form>; }
