import type { SupportedLocale } from "@/lib/i18n/config";

const copy = {
  en: {
    sections: ["Business", "Loyalty Program", "Rewards", "Brand Identity", "Loyalty Card", "Review & Launch"],
    step: "Step",
    of: "of",
    progressLabel: "Owner onboarding progress",
    navLabel: "Onboarding sections",
    fixField: "Please fix the highlighted field",
    businessName: "Business name",
    country: "Country",
    city: "City",
    businessPhone: "Business phone",
    phoneHint: "Local numbers are converted using the selected country code.",
    industry: "Business type or activity",
    industryPlaceholder: "e.g. Streaming",
    currency: "Currency",
    timezone: "Timezone",
    loyaltyMode: "Loyalty mode",
    visits: "Visits",
    points: "Points",
    salesAmount: "Sales amount",
    loyaltyUnit: "Loyalty unit",
    reward: "Reward",
    target: "Target",
    earnAmount: "Earn amount",
    identity: "Business identity",
    identityHint: "Logo and card branding are configured once in Loyalty Card.",
    cardHint: "Standard Card is enabled. Preview customer data is illustrative; the saved card always uses each customer’s live details.",
    changeLogo: "Change Logo",
    uploadLogo: "Upload Logo",
    logoError: "Logo must be a PNG, JPEG, or WebP image up to 500KB.",
    reviewHint: "Your progress is saved safely to your account. Launch creates your isolated business only after required setup is complete.",
    back: "Back",
    saveProgress: "Save progress",
    saved: "Progress saved.",
    saveFailed: "Could not save progress.",
    launch: "Launch",
    next: "Next",
  },
  ar: {
    sections: ["النشاط", "برنامج الولاء", "المكافآت", "هوية العلامة", "بطاقة الولاء", "المراجعة والإطلاق"],
    step: "الخطوة",
    of: "من",
    progressLabel: "تقدم إعداد حساب المالك",
    navLabel: "أقسام الإعداد",
    fixField: "يرجى تصحيح الحقل المحدد",
    businessName: "اسم النشاط",
    country: "الدولة",
    city: "المدينة",
    businessPhone: "هاتف النشاط",
    phoneHint: "يتم تحويل الرقم المحلي تلقائيًا باستخدام كود الدولة المختارة.",
    industry: "نوع النشاط",
    industryPlaceholder: "مثال: متجر أو مطعم",
    currency: "العملة",
    timezone: "المنطقة الزمنية",
    loyaltyMode: "نوع برنامج الولاء",
    visits: "الزيارات",
    points: "النقاط",
    salesAmount: "قيمة المبيعات",
    loyaltyUnit: "وحدة الولاء",
    reward: "المكافأة",
    target: "الهدف",
    earnAmount: "قيمة الكسب",
    identity: "هوية النشاط",
    identityHint: "يتم ضبط الشعار وهوية البطاقة مرة واحدة داخل قسم بطاقة الولاء.",
    cardHint: "البطاقة القياسية مفعلة. بيانات العميل في المعاينة توضيحية فقط، والبطاقة المحفوظة تستخدم بيانات كل عميل الفعلية.",
    changeLogo: "تغيير الشعار",
    uploadLogo: "رفع الشعار",
    logoError: "يجب أن يكون الشعار PNG أو JPEG أو WebP وبحجم لا يتجاوز 500KB.",
    reviewHint: "يتم حفظ تقدمك بأمان في حسابك. الإطلاق ينشئ نشاطك المعزول فقط بعد اكتمال البيانات المطلوبة.",
    back: "رجوع",
    saveProgress: "حفظ التقدم",
    saved: "تم حفظ التقدم.",
    saveFailed: "تعذر حفظ التقدم.",
    launch: "إطلاق",
    next: "التالي",
  },
} as const;

export function getOwnerOnboardingCopy(locale: SupportedLocale) {
  return copy[locale];
}
