import type { HTMLAttributes, ReactNode, TableHTMLAttributes, TdHTMLAttributes, ThHTMLAttributes } from "react";

import { cn } from "@/components/ui/utils";

export function TableContainer({ className, ...props }: HTMLAttributes<HTMLDivElement>) { return <div {...props} className={cn("max-w-full overflow-x-auto overscroll-contain rounded-lg border border-border bg-surface", className)} />; }
export function Table({ className, ...props }: TableHTMLAttributes<HTMLTableElement>) { return <table {...props} className={cn("w-full min-w-[40rem] border-collapse text-sm", className)} />; }
export function TableHeader({ className, ...props }: HTMLAttributes<HTMLTableSectionElement>) { return <thead {...props} className={cn("border-b border-border bg-surface-subtle", className)} />; }
export function TableBody({ className, ...props }: HTMLAttributes<HTMLTableSectionElement>) { return <tbody {...props} className={cn("divide-y divide-border", className)} />; }
export function TableRow({ className, selected = false, ...props }: HTMLAttributes<HTMLTableRowElement> & { selected?: boolean }) { return <tr {...props} aria-selected={selected || undefined} className={cn("transition-colors hover:bg-surface-subtle", selected && "bg-indigo-50", className)} />; }
export function TableHead({ className, numeric = false, sortable = false, children, ...props }: ThHTMLAttributes<HTMLTableCellElement> & { numeric?: boolean; sortable?: boolean }) { return <th {...props} scope={props.scope ?? "col"} aria-sort={sortable ? props["aria-sort"] ?? "none" : props["aria-sort"]} className={cn("px-4 py-3 text-start text-xs font-semibold uppercase tracking-wide text-slate-600", numeric && "text-end", className)}>{children}{sortable && <span aria-hidden="true" className="ms-1 text-slate-400">↕</span>}</th>; }
export function TableCell({ className, numeric = false, technical = false, ...props }: TdHTMLAttributes<HTMLTableCellElement> & { numeric?: boolean; technical?: boolean }) { return <td {...props} dir={technical ? "ltr" : props.dir} className={cn("px-4 py-3 align-middle text-start text-slate-700", numeric && "text-end lf-type-numeric", technical && "font-mono text-xs", className)} />; }
export function TableActions({ className, ...props }: HTMLAttributes<HTMLDivElement>) { return <div {...props} className={cn("flex items-center justify-end gap-1", className)} />; }
export function TableSkeleton({ columns = 4, rows = 5 }: { columns?: number; rows?: number }) { return <TableContainer aria-busy="true" aria-label="Loading table"><Table><TableBody>{Array.from({ length: rows }, (_, row) => <TableRow key={row}>{Array.from({ length: columns }, (_, column) => <TableCell key={column}><div aria-hidden="true" className="h-4 animate-pulse rounded bg-slate-200" /></TableCell>)}</TableRow>)}</TableBody></Table></TableContainer>; }
export function EmptyTableState({ children }: { children: ReactNode }) { return <div className="p-8 text-center text-sm text-slate-600">{children}</div>; }
