import type { AppLanguage } from "@/lib/i18n";

export function reportCopy(language: AppLanguage) {
  return language === "AR"
    ? {
        overview: "تقارير النشاط",
        staff: "أداء الفريق",
        export: "تصدير CSV",
        filters: "فلاتر التقرير",
        dateRange: "الفترة تشمل اليومين المحددين بتوقيت UTC.",
        apply: "تطبيق الفلاتر",
        reset: "إعادة ضبط",
        noData: "لا توجد بيانات ضمن هذه الفترة.",
        historical: "تحليل تاريخي",
        trends: "الاتجاهات اليومية",
        customerGrowth: "نمو العملاء",
        loyaltyTrend: "الولاء المكتسب والاستبدال",
        redemptions: "استبدالات المكافآت",
        earned: "مكتسب",
        redeemed: "مستبدل",
        customers: "عملاء",
        activity: "عمليات",
        summary: "ملخص الفترة",
        advanced: "تفاصيل وتحليلات موسعة",
        simple: "ملخص يومي واضح",
        exportUnavailable: "ليس لديك إذن تصدير البيانات.",
        totalCustomers: "إجمالي العملاء",
        withinSegment: "ضمن شريحة",
        allRegisteredCustomers: "كل العملاء المسجلين",
        newCustomers: "العملاء الجدد",
        registeredInPeriod: "تم تسجيلهم خلال الفترة المحددة",
        activeCustomers: "العملاء النشطون",
        customersWithLoyaltyActivity: "عملاء لديهم حركات ولاء",
        inactiveCustomers: "العملاء غير النشطين",
        inactivityRule: "حسب قاعدة عدم النشاط الحالية",
        atRiskCustomers: "عملاء معرّضون للتوقف",
        atRiskDetail: "توقف نشاطهم مؤخرًا ويحتاجون متابعة",
        operations: "الحركات",
        earnAndRedeemOperations: "عمليات الإضافة والاستبدال",
        earnedBalance: "رصيد الولاء المكتسب",
        earnOperation: "عملية إضافة",
        lifetimeEarned: "إجمالي الولاء المكتسب",
        sinceProgramStart: "منذ بداية البرنامج",
        totalTrackedSpend: "إجمالي الإنفاق المسجل",
        trackedSalesOnly: "محسوب فقط من عمليات البيع المسجلة في LoyalFlow",
        totalVisits: "إجمالي الزيارات",
        allRecordedVisits: "كل عمليات الإضافة المسجلة كزيارة",
        averageFirstReward: "متوسط الوقت لأول مكافأة",
        fromCustomerToFirstRedemption: "من إنشاء العميل حتى أول استبدال",
        averagePurchase: "متوسط قيمة الشراء",
        eligiblePurchaseAverage: "متوسط عمليات الشراء المؤهلة خلال الفترة",
        averageDaysBetweenVisits: "متوسط الأيام بين الزيارات",
        recordedVisitSpacing: "بين الزيارات المسجلة خلال الفترة المحددة",
        days: "يوم",
        redeemedRewards: "المكافآت المستبدلة",
        periodCost: "إجمالي التكلفة خلال الفترة",
        lifetimeTotal: "الإجمالي منذ البداية",
        unlockedRewards: "مكافآت فُتحت",
        unlockScopeDetail:
          "مقياس على مستوى النشاط؛ لا يحمل فتح المكافأة فرعًا أو موظفًا في السجل الحالي.",
        currentBalances: "أرصدة العملاء الحالية",
        availableBalanceTotal: "إجمالي الرصيد المتاح",
        returningCustomers: "العملاء العائدون",
        returningDetail: "عميل لديه عمليتا إضافة أو أكثر خلال الفترة",
        repeatCustomerRate: "معدل تكرار العملاء",
        repeatCustomerDetail:
          "العملاء ذوو عمليتي إضافة أو أكثر من العملاء النشطين بالولاء",
        recoveredCustomers: "العملاء المستعادون",
        recoveredDetail: "حسابات أعيد تفعيلها خلال الفترة",
        averageLoyaltyActivity: "متوسط نشاط الولاء",
        averageLoyaltyDetail: "عمليات إضافة لكل عميل نشط",
        redemptionRate: "معدل استبدال المكافآت",
        redemptionRateDetail: "نسبة الاستبدالات إلى عمليات الإضافة",
        impactEyebrow: "أثر برنامج الولاء",
        verifiedOperationalMetrics: "مؤشرات تشغيلية موثقة",
        impactDisclaimer:
          "تعرض هذه المؤشرات ما سجله LoyalFlow فقط. لا تنسب إيرادًا أو عائدًا للبرنامج ما لم يكن مسجلاً صراحةً كعملية بيع.",
        loyaltyOperations: "حركات ولاء مسجلة",
        loyaltyOperationsDetail: "إضافة، استبدال، أو تعديل ضمن الفترة",
        trackedLoyaltySales: "مبيعات ولاء مسجلة",
        trackedLoyaltySalesDetail:
          "مبيعات أدخلها الموظفون خلال الفترة، وليست إسنادًا تسويقيًا",
        twoOrMoreEarns: "عمليتا إضافة أو أكثر خلال الفترة",
        redemptionsInPeriod: "استبدالات مسجلة خلال الفترة",
        amongLoyaltyActive: "من العملاء ذوي نشاط الولاء",
        mostActive: "الأكثر نشاطًا",
        mostActiveDescription: "حسب كل حركات الولاء خلال الفترة.",
        movement: "حركة",
        highestEarned: "أعلى قيمة مكتسبة",
        highestEarnedDescription: "حسب الرصيد المكتسب خلال الفترة.",
        mostRedeemed: "الأكثر استبدالًا",
        mostRedeemedDescription: "حسب المكافآت المستبدلة خلال الفترة.",
        reward: "مكافأة",
        recentTransactions: "أحدث الحركات",
        recentTransactionsDetail: "أحدث 50 عملية خلال الفترة المحددة.",
        noTransactions: "لا توجد حركات خلال هذه الفترة.",
        customer: "العميل",
        type: "النوع",
        value: "القيمة",
        balance: "الرصيد",
        staffMember: "الموظف",
        date: "التاريخ",
        system: "النظام",
        addBalance: "إضافة رصيد",
        redeemReward: "استبدال مكافأة",
        adjustBalance: "تعديل رصيد",
        topCustomers: "أفضل العملاء",
        topCustomersDetail: "الترتيب حسب إجمالي رصيد الولاء المكتسب.",
        noCustomers: "لا يوجد عملاء حتى الآن.",
      }
    : {
        overview: "Business reports",
        staff: "Staff performance",
        export: "Export CSV",
        filters: "Report filters",
        dateRange: "The selected UTC dates are inclusive.",
        apply: "Apply filters",
        reset: "Reset",
        noData: "There is no data in this period.",
        historical: "Historical analysis",
        trends: "Daily trends",
        customerGrowth: "Customer growth",
        loyaltyTrend: "Loyalty earned and redeemed",
        redemptions: "Reward redemptions",
        earned: "Earned",
        redeemed: "Redeemed",
        customers: "Customers",
        activity: "Operations",
        summary: "Period summary",
        advanced: "Detailed historical analysis",
        simple: "A clear daily summary",
        exportUnavailable: "You do not have permission to export data.",
        totalCustomers: "Total customers",
        withinSegment: "Within segment",
        allRegisteredCustomers: "All registered customers",
        newCustomers: "New customers",
        registeredInPeriod: "Registered in the selected period",
        activeCustomers: "Active customers",
        customersWithLoyaltyActivity: "Customers with loyalty activity",
        inactiveCustomers: "Inactive customers",
        inactivityRule: "Based on the current inactivity rule",
        atRiskCustomers: "At-risk customers",
        atRiskDetail: "Recent activity dropped and needs follow-up",
        operations: "Operations",
        earnAndRedeemOperations: "Earn and redemption operations",
        earnedBalance: "Loyalty earned",
        earnOperation: "earn operation",
        lifetimeEarned: "Lifetime loyalty earned",
        sinceProgramStart: "since the programme started",
        totalTrackedSpend: "Total tracked spend",
        trackedSalesOnly: "Calculated only from sales recorded in LoyalFlow",
        totalVisits: "Total visits",
        allRecordedVisits: "All earn operations recorded as visits",
        averageFirstReward: "Average time to first reward",
        fromCustomerToFirstRedemption: "From customer creation to first redemption",
        averagePurchase: "Average purchase value",
        eligiblePurchaseAverage: "Average eligible purchase in the selected period",
        averageDaysBetweenVisits: "Average days between visits",
        recordedVisitSpacing: "Between visits recorded in the selected period",
        days: "days",
        redeemedRewards: "Redeemed rewards",
        periodCost: "Period cost",
        lifetimeTotal: "lifetime total",
        unlockedRewards: "Rewards unlocked",
        unlockScopeDetail:
          "Business-wide metric; reward unlocks do not carry branch or staff attribution in the current ledger.",
        currentBalances: "Current customer balances",
        availableBalanceTotal: "Total available balance",
        returningCustomers: "Returning customers",
        returningDetail: "Customer with two or more earn operations in the period",
        repeatCustomerRate: "Repeat customer rate",
        repeatCustomerDetail:
          "Customers with two or more earn operations among loyalty-active customers",
        recoveredCustomers: "Recovered customers",
        recoveredDetail: "Accounts reactivated in the selected period",
        averageLoyaltyActivity: "Average loyalty activity",
        averageLoyaltyDetail: "Earn operations per active customer",
        redemptionRate: "Reward redemption rate",
        redemptionRateDetail: "Redemptions as a share of earn operations",
        impactEyebrow: "Loyalty programme impact",
        verifiedOperationalMetrics: "Verified operational metrics",
        impactDisclaimer:
          "These metrics show only what LoyalFlow recorded. Revenue or return is not attributed to the programme unless it was explicitly recorded as a sale.",
        loyaltyOperations: "Recorded loyalty operations",
        loyaltyOperationsDetail: "Earn, redemption, or adjustment in the selected period",
        trackedLoyaltySales: "Recorded loyalty sales",
        trackedLoyaltySalesDetail:
          "Sales entered by staff in the selected period, not marketing attribution",
        twoOrMoreEarns: "Two or more earn operations in the period",
        redemptionsInPeriod: "Redemptions recorded in the selected period",
        amongLoyaltyActive: "Among customers with loyalty activity",
        mostActive: "Most active",
        mostActiveDescription: "By all loyalty operations in the selected period.",
        movement: "operation",
        highestEarned: "Highest earned value",
        highestEarnedDescription: "By loyalty balance earned in the selected period.",
        mostRedeemed: "Most redemptions",
        mostRedeemedDescription: "By rewards redeemed in the selected period.",
        reward: "reward",
        recentTransactions: "Recent transactions",
        recentTransactionsDetail: "Latest 50 operations in the selected period.",
        noTransactions: "There are no transactions in this period.",
        customer: "Customer",
        type: "Type",
        value: "Value",
        balance: "Balance",
        staffMember: "Staff",
        date: "Date",
        system: "System",
        addBalance: "Earn balance",
        redeemReward: "Redeem reward",
        adjustBalance: "Adjust balance",
        topCustomers: "Top customers",
        topCustomersDetail: "Ranked by lifetime loyalty earned.",
        noCustomers: "There are no customers yet.",
      };
}

export function safeReportNumber(value: number | null | undefined) {
  return Number.isFinite(value) ? value : 0;
}
