import type { LoyaltyMode } from "@/generated/prisma/client";
import type { AppLanguage } from "@/lib/i18n";

const dictionary = {
  AR: {
    customers: "العملاء", backToBusiness: "الرجوع للنشاط", backToCustomers: "الرجوع إلى العملاء", addCustomer: "إضافة عميل", scan: "مسح QR", reviewDuplicates: "مراجعة التكرارات", exportCustomers: "تصدير العملاء CSV", dashboard: "لوحة التحكم", customersLoadError: "تعذر تحميل العملاء", customerLoadError: "تعذر تحميل ملف العميل", customersLoadErrorDescription: "حاول مرة أخرى. لم تتغير أي بيانات للعميل.", customerLoadErrorDescription: "حاول مرة أخرى. لم تتغير أي عملية ولاء.",
    simpleDescription: "ابحث عن العميل وافتح ملفه لتسجيل عمليات اليوم.", advancedDescription: (business: string) => `إدارة ${business} وشرائحه وبياناته التشغيلية.`, customersCount: (count: number) => `${count} عميل`,
    created: "تم إنشاء العميل بنجاح.", invalidCustomer: "راجع بيانات العميل المدخلة.", invalidPhone: "أدخل رقم هاتف صحيحًا.", duplicatePhone: "رقم الهاتف مسجل بالفعل داخل هذا النشاط.", bulkInvalid: "لم تُنفّذ العملية: الاختيار أو الوسم غير صالح ضمن هذا النشاط.", bulkComplete: (selected: string, changed: string) => `تمت العملية الجماعية على ${selected} عميل؛ تغيّر ${changed} سجل.`,
    feedback: { earned: "تم تحديث رصيد الولاء بنجاح.", redeemed: "تم استبدال المكافأة بنجاح.", updated: "تم تحديث بيانات العميل بنجاح.", deactivated: "تم إيقاف حساب العميل بنجاح.", reactivated: "تم إعادة تفعيل حساب العميل بنجاح.", adjusted: "تم تعديل رصيد العميل بنجاح.", referralLink: "تم إنشاء رابط الإحالة للعميل.", tagAssigned: "تم حفظ وسم العميل.", tagRemoved: "تم إزالة وسم العميل.", noteCreated: "تمت إضافة الملاحظة الداخلية.", noteUpdated: "تم تعديل الملاحظة الداخلية.", adjustmentInvalid: "أدخل قيمة صحيحة وسببًا واضحًا.", adjustmentNegative: "لا يمكن أن يصبح الرصيد أقل من صفر.", duplicate: "رقم الهاتف مسجل بالفعل.", notEnough: "رصيد العميل غير كافٍ لاستبدال المكافأة.", rewardExpired: "انتهت صلاحية هذه المكافأة. الرصيد لم يتغير.", referral: "تعذر إنشاء رابط إحالة فريد. حاول مرة أخرى.", tagOrNoteInvalid: "أدخل نصًا صحيحًا للوسم أو الملاحظة.", earnedTooSoon: "تم منع إضافة متكررة بسرعة. تأكد من العملية ثم حاول مرة أخرى بعد ثوانٍ قليلة.", staffAttribution: "اختر موظفًا نشطًا من نفس النشاط قبل تسجيل العملية.", redeemedTooSoon: "تم منع استبدال مكرر بسرعة. تأكد من تسليم المكافأة ثم حاول مرة أخرى بعد ثوانٍ قليلة." },
    campaignSuggestion: { WELCOME: { title: "تم إنشاء العميل بنجاح 👋", description: "أرسل رسالة الترحيب ورابط كارت الولاء للعميل الجديد.", button: "إرسال رسالة الترحيب" }, REWARD_READY: { title: "المكافأة أصبحت جاهزة 🎁", description: "أرسل للعميل رسالة المكافأة الجاهزة للاستلام.", button: "إرسال رسالة المكافأة" }, ONE_AWAY: { title: "العميل على بُعد خطوة واحدة ✨", description: "ذكّر العميل بأن مكافأته قريبة لتشجيع الزيارة التالية.", button: "إرسال تذكير المكافأة" }, BALANCE_UPDATED: { title: "تم تحديث رصيد العميل", description: "أرسل للعميل رصيده الحالي والمتبقي للحصول على المكافأة.", button: "إرسال تحديث الرصيد" } },
    customerCodeHint: "سيتم إنشاء كود العميل ورابط الكارت تلقائيًا.", firstName: "الاسم الأول", lastName: "اسم العائلة", phone: "رقم الهاتف", firstNamePlaceholder: "محمد", lastNamePlaceholder: "أحمد",
    search: "البحث", searchPlaceholder: "الاسم أو الهاتف أو كود العميل", tag: "وسم العميل", allTags: "كل الوسوم", status: "الحالة", allCustomers: "كل العملاء", active: "نشط", inactive: "موقوف", segment: "شريحة العميل", allSegments: "كل الشرائح", sort: "الترتيب", newest: "الأحدث أولًا", oldest: "الأقدم أولًا", balanceHigh: "الأعلى رصيدًا", balanceLow: "الأقل رصيدًا", apply: "تطبيق",
    results: (first: number, last: number, count: number) => `عرض ${first}–${last} من ${count} نتيجة`, resetFilters: "مسح الفلاتر", activeFilters: "الفلاتر النشطة", searchFilter: "بحث", segmentFilter: "الشريحة", tagFilter: "الوسم", advancedOptions: "خيارات متقدمة", rewardReady: "مكافآت جاهزة", atRisk: "معرّضون للتوقف", suspendedAccounts: "حسابات موقوفة",
    noCustomers: "لا يوجد عملاء بعد", noResults: "لا توجد نتائج مطابقة", noCustomersDescription: "ابدأ بإضافة أول عميل لهذا النشاط.", noResultsDescription: "جرّب تغيير البحث أو الفلاتر.", showAllCustomers: "عرض كل العملاء", customerList: "قائمة العملاء", customer: "العميل", contact: "التواصل", loyalty: "الولاء", lastActivity: "آخر نشاط", action: "إجراء", progress: (value: number) => `التقدم ${value}%`, noActivity: "لا يوجد نشاط", noActivityYet: "لا يوجد نشاط بعد", openProfile: "فتح الملف", mobileCustomerList: "قائمة العملاء على الجوال", lastActivityDate: (date: string) => `آخر نشاط: ${date}`,
    profile: "ملف العميل", code: "الكود", loyaltyToday: "الولاء اليوم", rewardReadyNamed: (reward: string) => `المكافأة جاهزة: ${reward}`, remainingForReward: (remaining: number, reward: string) => `متبقي ${remaining} للحصول على ${reward}`, loyaltyAction: "إجراء ولاء", customerCard: "كارت العميل", toReachReward: "للوصول إلى المكافأة", rewardReadyToRedeem: "المكافأة جاهزة للاستبدال", openCustomerProfile: "فتح ملف العميل", previous: "السابق", next: "التالي",
    customerTags: "وسوم العميل", tagsDescription: "وسوم داخلية للتصفية والتنظيم، ولا تظهر على كارت العميل العام.", noTags: "لا توجد وسوم مضافة.", removeTag: (tag: string) => `إزالة وسم ${tag}`, newTagPlaceholder: "وسم جديد، مثال: VIP", add: "إضافة", notes: "ملاحظات داخلية", notesDescription: "لا تظهر هذه الملاحظات على كارت العميل أو عبر الرابط العام.", newInternalNote: "ملاحظة داخلية جديدة", notePlaceholder: "أضف ملاحظة لفريق العمل فقط", saveInternalNote: "حفظ ملاحظة داخلية", noNotes: "لا توجد ملاحظات داخلية.", deletedUser: "مستخدم محذوف", addedBy: (name: string, date: string) => `أضيفت بواسطة ${name} في ${date}`, lastEditedBy: (name: string) => ` · آخر تعديل بواسطة ${name}`, saveEdit: "حفظ التعديل",
    visits: "زيارات", points: "نقاط", salesAmount: "قيمة المبيعات", eligibleSales: "إجمالي الإنفاق المؤهل", visitsCount: "عدد الزيارات", pointsBalance: "رصيد النقاط", rewardsReady: (count: number) => `${count} مكافأة جاهزة 🎁`, remaining: (count: number) => `متبقي ${count}`, expired: "منتهية", ready: "جاهزة", rewardExpired: "انتهت صلاحية المكافأة", rewardValidUntil: (date: string) => `صالحة حتى ${date}`, rewardStartsOnUnlock: "تبدأ الصلاحية عند فتح المكافأة.", inactiveLoyaltyUnavailable: "حساب العميل موقوف، لذلك عمليات الولاء غير متاحة.", saleAmount: "قيمة عملية البيع", saleAmountPlaceholder: "مثال: 25000", recordSale: "تسجيل عملية البيع", addVisit: "+ إضافة زيارة", addPoints: (amount: number) => `+ إضافة ${amount} نقطة`,
    manageCustomer: "إدارة العميل", manageDescription: "تعديل بيانات العميل أو تغيير حالة الحساب.", saveCustomer: "حفظ تعديلات العميل", manualBalance: "تعديل الرصيد يدويًا", manualBalanceDescription: "استخدم هذا الخيار لتصحيح أخطاء الرصيد فقط، ويتم تسجيل كل تعديل.", currentBalance: (balance: number, unit: string) => `الرصيد الحالي: ${balance} ${unit}`, adjustmentType: "نوع التعديل", addBalance: "إضافة رصيد", subtractBalance: "خصم رصيد", amount: "القيمة", adjustmentReason: "سبب التعديل", adjustmentReasonPlaceholder: "مثال: تصحيح زيارة أُضيفت بالخطأ", saveBalanceAdjustment: "حفظ تعديل الرصيد", accountStatus: "حالة الحساب", inactiveAccountDescription: "العميل الموقوف لا يمكنه جمع الرصيد أو استبدال المكافآت.", deactivateCustomer: "إيقاف العميل", reactivateCustomer: "إعادة تفعيل العميل",
    timeline: "الخط الزمني للعميل", timelineDescription: "سجل موحّد لانضمام العميل وحركات الولاء وتغييرات حالة الحساب.", noEvents: "لا توجد أحداث حتى الآن.", requiresReview: "يتطلب مراجعة", by: (name: string) => `بواسطة ${name}`, balanceAfter: (balance: number | undefined) => `الرصيد بعد العملية: ${balance ?? ""}`,
    digitalCard: "كارت الولاء الرقمي", digitalCardDescription: "افتح الكارت أو أرسله للعميل.", retentionScore: "درجة الاحتفاظ (مؤشر قواعد)", veryLoyal: "ولاء مرتفع", retentionActive: "نشط", highRisk: "خطر توقف مرتفع", retentionDescription: "يعتمد على حداثة النشاط والتكرار والتقدم والاستبدال، وليس توقعًا بالذكاء الاصطناعي.", cardQrAlt: "رمز QR لكارت ولاء العميل", openCard: "فتح كارت العميل", copyLink: "نسخ الرابط", copied: "تم النسخ ✓", copyReferral: "نسخ رابط الإحالة", createReferral: "إنشاء رابط إحالة", welcomeMessage: "إرسال رسالة الترحيب", balanceMessage: "إرسال تحديث الرصيد", rewardMessage: "إرسال رسالة المكافأة", rewardMessageUnavailable: "رسالة المكافأة غير متاحة الآن", totalEarned: "إجمالي المكتسب", redeemedRewards: "المكافآت المستبدلة",
    savePending: "جارٍ الحفظ...", redeemReward: "استبدال المكافأة", redeemConfirm: "تأكيد استبدال المكافأة", redeemDescription: (cost: number, unit: string) => `سيتم خصم ${cost} ${unit} من رصيد العميل وتسجيل عملية الاستبدال في السجل.`, cancel: "إلغاء", confirmRedeem: "تأكيد الاستبدال", branch: "الفرع", selectBranch: "اختر فرعك", noBranch: "بدون نسبة لفرع", attributedStaff: "الموظف المنسوبة إليه العملية", selectStaff: "اختر موظفًا", noStaff: "بدون نسبة لموظف",
    bulkActions: "إجراءات جماعية للنتائج المعروضة", selectCustomers: "تحديد العملاء", selectedSummary: (selected: number, total: number) => `${selected} من ${total} محدد. الاختيار محدود لهذه الصفحة الحالية من نتائج البحث والفلاتر.`, selectCustomersDescription: "حدّد عميلًا أو أكثر لإظهار الإجراءات الجماعية المتاحة.", selectVisible: "تحديد المعروض", clearSelection: "مسح الاختيار", bulkAction: "الإجراء", addTag: "إضافة وسم", removeTagAction: "إزالة وسم", activateCustomers: "تفعيل العملاء", deactivateCustomers: "إيقاف العملاء", selectTag: "اختر وسمًا", runSelected: "تنفيذ على المحدد", exportSelected: "تصدير المحدد CSV", campaignSelected: "معاينة حملة للمحدد", confirmBulk: (operation: string, count: number) => `تأكيد ${operation} ${count} عميل؟`,
  },
  EN: {
    customers: "Customers", backToBusiness: "Back to business", backToCustomers: "Back to customers", addCustomer: "Add customer", scan: "Scan QR", reviewDuplicates: "Review duplicates", exportCustomers: "Export customers CSV", dashboard: "Dashboard", customersLoadError: "Unable to load customers", customerLoadError: "Unable to load customer profile", customersLoadErrorDescription: "Try again. No customer data was changed.", customerLoadErrorDescription: "Try again. No loyalty operation was changed.",
    simpleDescription: "Find a customer and open their profile to record today’s activity.", advancedDescription: (business: string) => `Manage ${business}, its segments, and operational customer data.`, customersCount: (count: number) => `${count} customers`,
    created: "Customer created successfully.", invalidCustomer: "Review the customer details.", invalidPhone: "Enter a valid phone number.", duplicatePhone: "This phone number is already registered for this business.", bulkInvalid: "The operation was not completed: the selection or tag is invalid for this business.", bulkComplete: (selected: string, changed: string) => `Bulk operation completed for ${selected} customers; ${changed} records changed.`,
    feedback: { earned: "Loyalty balance updated successfully.", redeemed: "Reward redeemed successfully.", updated: "Customer details updated successfully.", deactivated: "Customer account deactivated successfully.", reactivated: "Customer account reactivated successfully.", adjusted: "Customer balance adjusted successfully.", referralLink: "Customer referral link created.", tagAssigned: "Customer tag saved.", tagRemoved: "Customer tag removed.", noteCreated: "Internal note added.", noteUpdated: "Internal note updated.", adjustmentInvalid: "Enter a valid amount and a clear reason.", adjustmentNegative: "The balance cannot go below zero.", duplicate: "This phone number is already registered.", notEnough: "The customer balance is not enough to redeem this reward.", rewardExpired: "This reward has expired. The balance was not changed.", referral: "A unique referral link could not be created. Try again.", tagOrNoteInvalid: "Enter valid text for the tag or note.", earnedTooSoon: "A rapid duplicate earn was blocked. Confirm the operation and try again shortly.", staffAttribution: "Select an active staff member from this business before recording the operation.", redeemedTooSoon: "A rapid duplicate redemption was blocked. Confirm delivery, then try again shortly." },
    campaignSuggestion: { WELCOME: { title: "Customer created successfully 👋", description: "Send a welcome message and loyalty-card link to the new customer.", button: "Send welcome message" }, REWARD_READY: { title: "Reward is ready 🎁", description: "Send the customer a message that their reward is ready to collect.", button: "Send reward message" }, ONE_AWAY: { title: "Customer is one step away ✨", description: "Remind the customer that their reward is close to encourage the next visit.", button: "Send reward reminder" }, BALANCE_UPDATED: { title: "Customer balance updated", description: "Send the customer their current balance and remaining amount for the reward.", button: "Send balance update" } },
    customerCodeHint: "The customer code and card link are created automatically.", firstName: "First name", lastName: "Last name", phone: "Phone number", firstNamePlaceholder: "Mohammed", lastNamePlaceholder: "Ahmed",
    search: "Search", searchPlaceholder: "Name, phone, or customer code", tag: "Customer tag", allTags: "All tags", status: "Status", allCustomers: "All customers", active: "Active", inactive: "Inactive", segment: "Customer segment", allSegments: "All segments", sort: "Sort", newest: "Newest first", oldest: "Oldest first", balanceHigh: "Highest balance", balanceLow: "Lowest balance", apply: "Apply",
    results: (first: number, last: number, count: number) => `Showing ${first}–${last} of ${count} results`, resetFilters: "Reset filters", activeFilters: "Active filters", searchFilter: "Search", segmentFilter: "Segment", tagFilter: "Tag", advancedOptions: "Advanced options", rewardReady: "Rewards ready", atRisk: "At risk", suspendedAccounts: "Inactive accounts",
    noCustomers: "No customers yet", noResults: "No matching results", noCustomersDescription: "Start by adding the first customer for this business.", noResultsDescription: "Try changing the search or filters.", showAllCustomers: "Show all customers", customerList: "Customer list", customer: "Customer", contact: "Contact", loyalty: "Loyalty", lastActivity: "Last activity", action: "Action", progress: (value: number) => `Progress ${value}%`, noActivity: "No activity", noActivityYet: "No activity yet", openProfile: "Open profile", mobileCustomerList: "Mobile customer list", lastActivityDate: (date: string) => `Last activity: ${date}`,
    profile: "Customer profile", code: "Code", loyaltyToday: "Loyalty today", rewardReadyNamed: (reward: string) => `Reward ready: ${reward}`, remainingForReward: (remaining: number, reward: string) => `${remaining} remaining for ${reward}`, loyaltyAction: "Loyalty action", customerCard: "Customer card", toReachReward: "to reach the reward", rewardReadyToRedeem: "Reward ready to redeem", openCustomerProfile: "Open customer profile", previous: "Previous", next: "Next",
    customerTags: "Customer tags", tagsDescription: "Internal tags for filtering and organization; they are not shown on the public customer card.", noTags: "No tags added.", removeTag: (tag: string) => `Remove tag ${tag}`, newTagPlaceholder: "New tag, e.g. VIP", add: "Add", notes: "Internal notes", notesDescription: "These notes are not shown on the customer card or public link.", newInternalNote: "New internal note", notePlaceholder: "Add a note for the team only", saveInternalNote: "Save internal note", noNotes: "No internal notes.", deletedUser: "Deleted user", addedBy: (name: string, date: string) => `Added by ${name} on ${date}`, lastEditedBy: (name: string) => ` · Last edited by ${name}`, saveEdit: "Save changes",
    visits: "Visits", points: "Points", salesAmount: "Sales amount", eligibleSales: "Eligible sales total", visitsCount: "Visit count", pointsBalance: "Points balance", rewardsReady: (count: number) => `${count} rewards ready 🎁`, remaining: (count: number) => `${count} remaining`, expired: "Expired", ready: "Ready", rewardExpired: "Reward expired", rewardValidUntil: (date: string) => `Valid until ${date}`, rewardStartsOnUnlock: "Validity starts when the reward is unlocked.", inactiveLoyaltyUnavailable: "This customer account is inactive, so loyalty operations are unavailable.", saleAmount: "Sale amount", saleAmountPlaceholder: "e.g. 25000", recordSale: "Record sale", addVisit: "+ Add visit", addPoints: (amount: number) => `+ Add ${amount} points`,
    manageCustomer: "Manage customer", manageDescription: "Edit customer details or change account status.", saveCustomer: "Save customer changes", manualBalance: "Manual balance adjustment", manualBalanceDescription: "Use this only to correct balance errors; every adjustment is recorded.", currentBalance: (balance: number, unit: string) => `Current balance: ${balance} ${unit}`, adjustmentType: "Adjustment type", addBalance: "Add balance", subtractBalance: "Subtract balance", amount: "Amount", adjustmentReason: "Adjustment reason", adjustmentReasonPlaceholder: "e.g. Correct a visit added by mistake", saveBalanceAdjustment: "Save balance adjustment", accountStatus: "Account status", inactiveAccountDescription: "An inactive customer cannot earn balance or redeem rewards.", deactivateCustomer: "Deactivate customer", reactivateCustomer: "Reactivate customer",
    timeline: "Customer timeline", timelineDescription: "A unified record of customer enrollment, loyalty activity, and account-status changes.", noEvents: "No events yet.", requiresReview: "Needs review", by: (name: string) => `By ${name}`, balanceAfter: (balance: number | undefined) => `Balance after: ${balance ?? ""}`,
    digitalCard: "Digital loyalty card", digitalCardDescription: "Open the card or send it to the customer.", retentionScore: "Retention score (rules-based)", veryLoyal: "Very loyal", retentionActive: "Active", highRisk: "High churn risk", retentionDescription: "Based on activity recency, frequency, progress, and redemption; it is not an AI prediction.", cardQrAlt: "QR code for the customer loyalty card", openCard: "Open customer card", copyLink: "Copy link", copied: "Copied ✓", copyReferral: "Copy referral link", createReferral: "Create referral link", welcomeMessage: "Send welcome message", balanceMessage: "Send balance update", rewardMessage: "Send reward message", rewardMessageUnavailable: "Reward message is not available now", totalEarned: "Total earned", redeemedRewards: "Rewards redeemed",
    savePending: "Saving...", redeemReward: "Redeem reward", redeemConfirm: "Confirm reward redemption", redeemDescription: (cost: number, unit: string) => `${cost} ${unit} will be deducted from the customer balance and the redemption will be recorded.`, cancel: "Cancel", confirmRedeem: "Confirm redemption", branch: "Branch", selectBranch: "Select your branch", noBranch: "No branch attribution", attributedStaff: "Attributed staff member", selectStaff: "Select a staff member", noStaff: "No staff attribution",
    bulkActions: "Bulk actions for visible results", selectCustomers: "Select customers", selectedSummary: (selected: number, total: number) => `${selected} of ${total} selected. Selection is limited to this current page of search and filter results.`, selectCustomersDescription: "Select one or more customers to see available bulk actions.", selectVisible: "Select visible", clearSelection: "Clear selection", bulkAction: "Action", addTag: "Add tag", removeTagAction: "Remove tag", activateCustomers: "Activate customers", deactivateCustomers: "Deactivate customers", selectTag: "Select a tag", runSelected: "Run for selected", exportSelected: "Export selected CSV", campaignSelected: "Preview campaign for selected", confirmBulk: (operation: string, count: number) => `Confirm ${operation} for ${count} customers?`,
  },
} as const;

export type CustomerUiCopy = (typeof dictionary)[AppLanguage];

export function customerUiCopy(language: AppLanguage): CustomerUiCopy {
  return dictionary[language];
}

export function getLoyaltyModeLabel(language: AppLanguage, mode: LoyaltyMode) {
  const copy = customerUiCopy(language);
  return mode === "VISITS" ? copy.visits : mode === "POINTS" ? copy.points : copy.salesAmount;
}
