import type { AppLanguage } from "@/lib/i18n";

const dictionary = {
  AR: {
    backToBusiness: "الرجوع إلى النشاط",
    scan: "مسح",
    scanner: "ماسح LoyalFlow",
    scanCustomerCard: "مسح كارت العميل",
    scanDescription: "افتح الكاميرا ووجّهها ناحية QR الموجود على كارت العميل. بعد القراءة هيفتح ملف العميل مباشرة لإضافة زيارة أو استبدال الهدية.",
    cameraInstruction: "وجّه الكاميرا ناحية QR الخاص بالعميل.",
    processing: "جارٍ البحث عن العميل...",
    authenticationRequired: "يجب تسجيل الدخول أولًا.",
    invalidQrInput: "رمز QR أو البيانات المدخلة غير صحيحة.",
    permissionDenied: "ليس لديك صلاحية لفتح هذا العميل.",
    rateLimited: "تم تجاوز عدد المحاولات المسموح. حاول مرة أخرى قريبًا.",
    customerOrCardNotFound: "العميل أو الكارت غير موجود.",
    genericError: "تعذر قراءة هذا الكارت.",
    secureContextWarning: "تشغيل الكاميرا على الهاتف يحتاج رابط HTTPS. يمكنك حاليًا اختيار صورة QR من الهاتف أو لصق رابط الكارت يدويًا.",
    cameraUnavailable: "الكاميرا غير متاحة على هذا الجهاز. يمكنك اختيار صورة QR أو استخدام البحث.",
    cameraPermissionDenied: "تم رفض إذن الكاميرا. اسمح بالوصول إلى الكاميرا ثم أعد المحاولة.",
    scannerInitializationFailed: "تعذر تشغيل الماسح الآن. حاول مرة أخرى أو استخدم البحث.",
    retryCamera: "إعادة تشغيل الكاميرا",
    scannerStatus: "حالة ماسح QR",
    manualDivider: "أو",
    manualLabel: "الصق رابط الكارت أو الرمز التعريفي يدويًا",
    manualPlaceholder: "رابط الكارت أو الرمز التعريفي",
    openCustomer: "فتح العميل",
    customerSearchHeading: "البحث عن عميل",
    customerSearchDescription: "ابحث بالاسم أو رقم الهاتف أو كود العميل.",
    customerSearchLabel: "البحث عن عميل",
    customerSearchPlaceholder: "الاسم أو الهاتف أو كود العميل",
    customerSearchMinimum: "اكتب حرفين على الأقل للبحث.",
    customerSearching: "جارٍ البحث عن العملاء...",
    customerSearchEmpty: "لا يوجد عميل نشط مطابق في هذا النشاط.",
    customerSearchOpen: "فتح العميل",
    clearCustomerSearch: "مسح البحث",
    customerSearchError: "تعذر البحث عن العملاء. حاول مرة أخرى.",
    customerCard: "كارت العميل",
    backToScanner: "الماسح",
    operationRecorded: "✅ تم تسجيل العملية بنجاح",
    rewardRedeemed: "🎁 تم استبدال المكافأة بنجاح",
    operationError: "حدث خطأ، حاول مرة أخرى",
    balance: "الرصيد الحالي",
    activity: "آخر النشاطات",
    noActivity: "لا يوجد نشاط بعد",
    earnOperation: "تسجيل عملية جديدة",
    addSale: "💰 إضافة عملية بيع",
    addVisit: "👋 تسجيل زيارة",
    addPoints: "⭐ إضافة نقاط ولاء",
    saleAmountPlaceholder: "قيمة البيع",
    recordSale: "تسجيل عملية بيع",
    addVisitAction: "+ إضافة زيارة",
    addPointsAction: (amount: number) => `+ إضافة ${amount} نقطة`,
    availableRewards: "🎁 المكافآت المتاحة",
    rewardCode: "الكود",
    redeemReward: "استبدال المكافأة",
    pendingAction: "جارٍ التنفيذ...",
    scanNext: "📷 مسح عميل جديد",
    openFullProfile: "فتح ملف العميل الكامل",
    earnActivity: "كسب ولاء",
    redeemActivity: "استبدال مكافأة",
    adjustmentActivity: "تعديل يدوي",
    loyaltyOperation: "عملية ولاء",
    by: "بواسطة",
  },
  EN: {
    backToBusiness: "Back to business",
    scan: "Scan",
    scanner: "LoyalFlow scanner",
    scanCustomerCard: "Scan customer card",
    scanDescription: "Open the camera and point it at the QR code on the customer card. After it is read, the customer profile opens so you can record a visit or redeem a reward.",
    cameraInstruction: "Point the camera at the customer QR code.",
    processing: "Finding customer...",
    authenticationRequired: "Authentication is required.",
    invalidQrInput: "The QR code or input is invalid.",
    permissionDenied: "You do not have permission to open this customer.",
    rateLimited: "Too many attempts. Please try again shortly.",
    customerOrCardNotFound: "The customer or card could not be found.",
    genericError: "This card could not be read.",
    secureContextWarning: "Camera access on mobile requires an HTTPS link. You can still select a QR image from your phone or paste the card link manually.",
    cameraUnavailable: "The camera is unavailable on this device. You can select a QR image or use search.",
    cameraPermissionDenied: "Camera permission was denied. Allow camera access and try again.",
    scannerInitializationFailed: "The scanner could not start. Try again or use search.",
    retryCamera: "Restart camera",
    scannerStatus: "QR scanner status",
    manualDivider: "or",
    manualLabel: "Paste the card link or identifier manually",
    manualPlaceholder: "Card link or identifier",
    openCustomer: "Open customer",
    customerSearchHeading: "Find a customer",
    customerSearchDescription: "Search by name, phone number, or customer code.",
    customerSearchLabel: "Find a customer",
    customerSearchPlaceholder: "Name, phone, or customer code",
    customerSearchMinimum: "Enter at least 2 characters to search.",
    customerSearching: "Searching customers...",
    customerSearchEmpty: "No active customer matches this search.",
    customerSearchOpen: "Open customer",
    clearCustomerSearch: "Clear search",
    customerSearchError: "Customers could not be searched. Try again.",
    customerCard: "Customer card",
    backToScanner: "Scanner",
    operationRecorded: "✅ Operation recorded successfully",
    rewardRedeemed: "🎁 Reward redeemed successfully",
    operationError: "Something went wrong. Try again.",
    balance: "Current balance",
    activity: "Recent activity",
    noActivity: "No activity yet",
    earnOperation: "Record a new operation",
    addSale: "💰 Add sale",
    addVisit: "👋 Record visit",
    addPoints: "⭐ Add loyalty points",
    saleAmountPlaceholder: "Sale amount",
    recordSale: "Record sale",
    addVisitAction: "+ Add visit",
    addPointsAction: (amount: number) => `+ Add ${amount} points`,
    availableRewards: "🎁 Available rewards",
    rewardCode: "Code",
    redeemReward: "Redeem reward",
    pendingAction: "Processing...",
    scanNext: "📷 Scan next customer",
    openFullProfile: "Open full customer profile",
    earnActivity: "Loyalty earned",
    redeemActivity: "Reward redeemed",
    adjustmentActivity: "Manual adjustment",
    loyaltyOperation: "Loyalty operation",
    by: "By",
  },
} as const;

export type ScanCopy = (typeof dictionary)[AppLanguage];

export function scanUiCopy(language: AppLanguage): ScanCopy {
  return dictionary[language];
}
